# Site settings
email: "transient.tran@gmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-98360321-1

# SEO settings
title: Trandromeda Online
description: One more drop in the universe
url: "trandromeda.github.io"
twitter_username: andyxtran
default_img: http://i.imgur.com/0R8FbnE.jpg

# Profile settings
name: Andy Tran
profile_img: http://i.imgur.com/0R8FbnE.jpg
profile: I'm a health researcher turned web developer. Now I want to use my skills and experience to build things that will improve people's livelihoods. Based in Toronto, with my eyes set on the world.
social:
  github: https://github.com/trandromeda
  linkedin: https://ca.linkedin.com/in/andy-tran-48580b1a
  instagram: https://www.instagram.com/trandromeda/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
