# Site settings
email: "transient.tran@gmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trandromeda
description: One more drop in the universe
url: ""
twitter_username: andyxtran
default_img: 

# Profile settings
name: Andy Tran
profile_img: 
profile: My real name is Andy Tran
social:
  github: https://github.com/trandromeda

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
